version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PSQL_PORT}:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  app:
    build: ./backend
    container_name: springboot-app
    restart: unless-stopped
    expose:
      - "8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_BOOT_PORT: 8080
    env_file:
      - ./.env

  frontend-dev:
    image: node:22-alpine
    container_name: frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${REACT_PORT}:5173"
    command: >
      sh -c "corepack enable &&
             corepack prepare pnpm@10.15.0 --activate &&
             pnpm install &&
             pnpm dev --host --port 5173"
    depends_on:
      - app

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro 
    depends_on:
      - app
    env_file:
      - .env